name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - run: npm i
      - run: cd client && npm i
      - run: cd server && npm i
      - run: npm run build
      - run: pm2 restart mmrs
